/*
 * This source file was generated by the Gradle 'init' task
 */
package jv.dio;

import java.util.ArrayList;
import java.util.List;
import jv.dio.br.com.Aula1;
import jv.dio.br.com.Aula2;
import jv.dio.br.com.Aula;
public class App {
    

    public static void main(String[] args) {
        List<Aula> aulas = new ArrayList<>();
        aulas.add(new Aula1());
        aulas.add(new Aula2());
        for (Aula aula : aulas) {
            aula.execute();
        }
    }
}
